exports.CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
exports.CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
exports.CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL"

exports.MY_ORDERS_REQUEST = "MY_ORDERS_REQUEST"
exports.MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS"
exports.MY_ORDERS_FAIL = "MY_ORDERS_FAIL"

exports.ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST";
exports.ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS";
exports.ALL_ORDERS_FAIL = "ALL_ORDERS_FAIL";

exports.UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
exports.UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
exports.UPDATE_ORDER_RESET = "UPDATE_ORDER_RESET";
exports.UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL";

exports.DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
exports.DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
exports.DELETE_ORDER_RESET = "DELETE_ORDER_RESET";
exports.DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";

exports.ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
exports.ORDER_DETAILS_SUCCESS = "ORDEER_DETAILS_SUCCESS"
exports.ORDER_DETAILS_FAIL = "ORDEER_DETAILS_FAIL"



exports.CLEAR_ERRORS = "CLEAR_ERRORS"