const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"
const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"

const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL"
const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST"
const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS"

const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET";
const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL";

const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";
const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST"
const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL"
const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET"

const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL"
const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
const CLEAR_ERRORS = "CLEAR_ERRORS"

const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";


module.exports = {
    ALL_PRODUCT_FAIL, ALL_PRODUCT_REQUEST, ALL_PRODUCT_SUCCESS, CLEAR_ERRORS,
    PRODUCT_DETAILS_FAIL, PRODUCT_DETAILS_REQUEST, PRODUCT_DETAILS_SUCCESS
    , NEW_REVIEW_FAIL, NEW_REVIEW_REQUEST, NEW_REVIEW_RESET, NEW_REVIEW_SUCCESS,
    ADMIN_PRODUCT_FAIL, ADMIN_PRODUCT_REQUEST, ADMIN_PRODUCT_SUCCESS,
    NEW_PRODUCT_FAIL, NEW_PRODUCT_REQUEST, NEW_PRODUCT_SUCCESS, NEW_PRODUCT_RESET,
    DELETE_PRODUCT_FAIL, DELETE_PRODUCT_REQUEST, DELETE_PRODUCT_RESET, DELETE_PRODUCT_SUCCESS,
    UPDATE_PRODUCT_SUCCESS, UPDATE_PRODUCT_REQUEST, UPDATE_PRODUCT_FAIL, UPDATE_PRODUCT_RESET,
    ALL_REVIEW_FAIL, ALL_REVIEW_REQUEST, ALL_REVIEW_SUCCESS, DELETE_REVIEW_FAIL, DELETE_REVIEW_REQUEST,
    DELETE_REVIEW_RESET, DELETE_REVIEW_SUCCESS
}
