exports.LOGIN_REQUEST = "LOGIN_REQUEST"
exports.LOGIN_SUCCESS = "LOGIN_SUCCESS"
exports.LOGIN_FAIL = "LOGIN_FAIL"
exports.CLEAR_ERRORS = "CLEAR_ERRORS"

exports.REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
exports.REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
exports.REGISTER_USER_FAIL = "REGISTER_USER_FAIL"

exports.LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
exports.LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"
exports.LOAD_USER_FAIL = "LOAD_USER_FAIL"

exports.LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
exports.LOGOUT_FAIL = "LOGOUT_FAIL"

exports.UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
exports.UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL"
exports.UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET"
exports.UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"


exports.UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST"
exports.UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL"
exports.UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET"
exports.UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS"

exports.FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST"
exports.FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
exports.FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL"

exports.RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
exports.RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
exports.RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

exports.ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
exports.ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
exports.ALL_USERS_FAIL = "ALL_USERS_FAIL";

exports.USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
exports.USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
exports.USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

exports.UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
exports.UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
exports.UPDATE_USER_RESET = "UPDATE_USER_RESET";
exports.UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

exports.DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
exports.DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
exports.DELETE_USER_FAIL = "DELETE_USER_FAIL";
exports.DELETE_USER_RESET = "DELETE_USER_RESET";

